Models/ErrorViewModel.cs
using System;

namespace MVC1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MusicDB.cs
namespace MVC1.Models
{
    public class MusicDB
    {
        public int ID { get; set; }
        public string Album { get; set; }
        public string Artist { get; set; }
    }
}

Models/MusicDBContext.cs
using System;
using Microsoft.EntityFrameworkCore;

namespace MVC1.Models
{
    public class MusicDBContext : DbContext
    {
        public MusicDBContext(DbContextOptions<MusicDBContext> options)
            : base(options)
        {
        }

        public DbSet<MusicDB> Album { get; set; }
        public DbSet<MusicDB> Artist { get; set; }
    }
}

Models/SeedData.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using System;
using System.Linq;

namespace MVC1.Models
{
    public static class SeedData
    {
        public static void Initialize(IServiceProvider serviceProvider)
        {
            using (var context = new MusicDBContext(
                serviceProvider.GetRequiredService<DbContextOptions<MusicDBContext>>()))
            {
                // Look for any MusicDB entries:
                if (context.Album.Any())
                {
                    return;   // DB has been seeded
                }

                context.AddRange(
                    new MusicDB
                    {
                        Album = "Emerson, Lake, & Palmer",
                        Artist = "Emerson, Lake, & Palmer"
                    },
                    new MusicDB
                    {
                        Album = "Tarkus",
                        Artist = "Emerson, Lake, & Palmer"
                    },
                    new MusicDB
                    {
                        Album = "Pictures At An Exhibition",
                        Artist = "Emerson, Lake, & Palmer"
                    },
                    new MusicDB
                    {
                        Album = "Trilogy",
                        Artist = "Emerson, Lake, & Palmer"
                    },
                    new MusicDB
                    {
                        Album = "Brain Salad Surgery",
                        Artist = "Emerson, Lake, & Palmer"
                    }

                );
                context.SaveChanges();
            }
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC1.Models;

namespace MVC1.Controllers
{
    public class HomeController : Controller
    {
        // calls Views/Home/Index.cshtml:
        public IActionResult Index()
        {
            return View();
        }

        // calls Views/Home/About.cshtml:
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        // calls Views/Home/Contact.cshtml:
        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        // calls Views/Home/Privacy.cshtml:
        public IActionResult Privacy()
        {
            return View();
        }

        // Don't know what this does:
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]

        // calls Views/Shared/Error.cshtml:
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MusicDBController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MVC1.Models;

namespace MVC1.Controllers
{
    public class MusicDBController : Controller
    {
        readonly MusicDBContext _context;

        public MusicDBController(MusicDBContext context)
        {
            _context = context;
        }

        // GET: MusicDB
        public async Task<IActionResult> Index()
        {
            return View(await _context.Album.ToListAsync());
        }

        // GET: MusicDB/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicDB = await _context.Album
                .FirstOrDefaultAsync(m => m.ID == id);
            if (musicDB == null)
            {
                return NotFound();
            }

            return View(musicDB);
        }

        // GET: MusicDB/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MusicDB/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Album,Artist")] MusicDB musicDB)
        {
            if (ModelState.IsValid)
            {
                _context.Add(musicDB);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(musicDB);
        }

        // GET: MusicDB/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicDB = await _context.Album.FindAsync(id);
            if (musicDB == null)
            {
                return NotFound();
            }
            return View(musicDB);
        }

        // POST: MusicDB/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Album,Artist")] MusicDB musicDB)
        {
            if (id != musicDB.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(musicDB);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MusicDBExists(musicDB.ID))
                    {
                        return NotFound();
                    }
                    throw;
                }
                return RedirectToAction(nameof(Index));
            }
            return View(musicDB);
        }

        // GET: MusicDB/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var musicDB = await _context.Album
                .FirstOrDefaultAsync(m => m.ID == id);
            if (musicDB == null)
            {
                return NotFound();
            }

            return View(musicDB);
        }

        // POST: MusicDB/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var musicDB = await _context.Album.FindAsync(id);
            _context.Album.Remove(musicDB);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        bool MusicDBExists(int id)
        {
            return _context.Album.Any(e => e.ID == id);
        }
    }
}

Views/Home/About.cshtml
@{
    ViewData["Title"] = "Views/Home/About.cshtml";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Views/Home/Contact.cshtml";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    953 Trumbull St<br />
    Deltona, FL 32725<br />
    <abbr title="Phone">P:</abbr>
    386.315.4656
</address>

<address>
    <strong>Support:</strong> <a href="mailto:perk32725@gmail.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:perk32725@gmail.com">Marketing@example.com</a>
</address>

Views/Home/Index.cshtml
@{
    // this lands in the tab:
    ViewData["Title"] = "Views/Home/Index.cshtml";
}

@* The Carousel: *@
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

@* Documentation links: *@
<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

Views/MusicDB/Catalog.cshtml
@{
    ViewData["Title"] = "Views/MusicDB/Catalog.cshtml";
}
<h2>Catalog</h2>
<p>Views/MusicDB/Catalog.cshtml</p>

<ul>
    Catalog.cshtml: ViewData["MainMsg"] is:
    <li>@ViewData["MainMsg"]</li>
</ul>

Views/MusicDB/Create.cshtml
@model MVC1.Models.MusicDB

@{
    ViewData["Title"] = "Views/MusicDB/Create.cshtml";
}

<h2>Views/MusicDB/Create</h2>

<h4>MusicDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MusicDB/Delete.cshtml
@model MVC1.Models.MusicDB

@{
    ViewData["Title"] = "Views/MusicDB/Delete.cshtml";
}

<h2>Views/MusicDB/Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MusicDB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/MusicDB/Details.cshtml
@model MVC1.Models.MusicDB

@{
    ViewData["Title"] = "Views/MusicDB/Details.cshtml";
}

<h2>Views/MusicDB/Details</h2>

<div>
    <h4>MusicDB</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Album)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Album)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Artist)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/MusicDB/Edit.cshtml
@model MVC1.Models.MusicDB

@{
    ViewData["Title"] = "Views/MusicDB/Edit.cshtml";
}

<h2>Views/MusicDB/Edit</h2>

<h4>MusicDB</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Album" class="control-label"></label>
                <input asp-for="Album" class="form-control" />
                <span asp-validation-for="Album" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Artist" class="control-label"></label>
                <input asp-for="Artist" class="form-control" />
                <span asp-validation-for="Artist" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MusicDB/Index.cshtml
@model IEnumerable<MVC1.Models.MusicDB>

@{
    // this lands in the tab:
    ViewData["Title"] = "Views/MusicDB/Index.cshtml";
}

@* this is the main heading on the page: *@
<h2>Views/MusicDB/Index.cshtml</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Album) @* display album *@
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist) @* display artist *@
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Album) @* display album *@
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist) @* display artist *@
            </td>
            <td>
                @* set up action links: *@
                @* Details could be used to display tracklist *@
                <a asp-action="Edit"    asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete"  asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - MVC1/MusicDB</title>

        <environment include="Development">
            <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
            <link rel="stylesheet" href="~/css/site.css" />
        </environment>
        <environment exclude="Development">
            <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @* 
                    replace the first item in the titlebar with our stuff:
                    <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">MVC1</a>
                    *@
                    <a asp-area="" asp-controller="MusicDB" asp-action="Index" class="navbar-brand">MVC1/MusicDB</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <partial name="_CookieConsentPartial" />

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - MVC1</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
</html>